http:
  port: 8080
https:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  authenticationAPI:
    host: 'localhost'
    paths:
      - '/api/Token'
      - '/api/autorization'
  paymentAPI:
    host: 'localhost'
    paths:
      - '/api/v1/public/payment'
      - '/testes'
  httpbin:
    host: 'localhost'
    paths:
      - '/ip'
serviceEndpoints:
  authenticationService:
    url: 'http://localhost:52016'
  paymentService:
    url: 'https://api-payment.herokuapp.com'
  exampleService:
    url: 'http://httpbin.org/'
policies:
  - proxy
pipelines:
  - name: authentication
    apiEndpoints:
      - authenticationAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: authenticationService
  - name: payment
    apiEndpoints:
      - paymentAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: paymentService
            changeOrigin: true
  - name: example
    apiEndpoints:
      - httpbin
    policies:
      - proxy:
        - action:
            serviceEndpoint: exampleService