http:
  port: ${PORT}
https:
  port: ${PORT}
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  authenticationAPI:
    host: ${HOST}
    paths:
      - '/authentication/*'
  paymentAPI:
    host: ${HOST}
    paths:
      - '/api/v1/public/payment'
      - '/testes'
  httpbin:
    host: ${HOST}
    paths:
      - '/ip'
      - '/meuip'
      - '/teste/*'
serviceEndpoints:
  authenticationService:
    url: 'http://localhost:52016'
  paymentService:
    url: 'https://api-payment.herokuapp.com'
  exampleService:
    url: 'http://httpbin.org/'
policies:
  - expression
  - proxy
pipelines:
  - name: authentication
    apiEndpoints:
      - authenticationAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: authenticationService
  - name: payment
    apiEndpoints:
      - paymentAPI
    policies:
      - proxy:
        - action:
            serviceEndpoint: paymentService
            changeOrigin: true
  - name: example
    apiEndpoints:
      - httpbin
    policies:
      - expression:
        - action:
            jscode: |
              if (req.url.startsWith('/teste')) {
                const newURL = req.url.replace(/\/teste/, '');
                req.url = newURL;
              }
      - proxy:
        - action:
            serviceEndpoint: exampleService